name: Tests
on:
  push:
    branches: master
  pull_request:
    branches: master
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: node:20-alpine
    defaults:
      run:
        working-directory: frontend
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: yarn install
    - name: Run tests
      run: yarn test
