name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: Create index.html
        run: |
          mkdir -p .reg
          echo '<!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Document</title>
          </head>
          <body>
              <h1>Hello World</h1>
          </body>
          </html>' > .reg/index.html
    - name: Verify index.html
      run: cat .reg/index.html
    - name: deploy report to github page
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .reg/
        destination_dir: ${{ github.head_ref  }} # PR毎にディレクトリを分けることで上書きを防ぐ

    - name: find comment
      uses: peter-evans/find-comment@v2
      id: fc
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'github-actions[bot]'
        body-includes: reg-suit report
