name: test2
on:
  pull_request:
permissions:
  contents: write
  pull-requests: write
  id-token: write
  pages: write
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: Create index.html
      run: |
        mkdir -p .reg
        echo '<!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Document</title>
        </head>
        <body>
            <h1>Hello World3</h1>
        </body>
        </html>' > .reg/index.html
    - name: Verify index.html
      run: cat .reg/index.html
    - name: deploy report to github page artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: .reg
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1
